### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by nliautaud** [nliautaud/gametimer#1]
- [x] Add or remove timers
- [x] Switch players on tap
- [x] Play / pause
- [x] Reset timers
- [x] Settings
- [x] Maximum time by player (chess clock)
- [ ] Maximum time by turn
- [x] Countdown mode
- [ ] Stop/continue on time out
- [ ] Turns counter
- [x] Players colors
- [ ] Alarms
- [x] Prevent device sleep (wake lock)
- [ ] Multiple orientations / layouts (one-sided, face-to-face, around table...)
- [x] Internationalisation (english / french)
- [x] Persistant settings
- [ ] Light mode
- [ ] PWA customization (icon, colors...)
- [ ] Doc / readme
